### ISSUE TITLE
User Type resolver tests

### ISSUE THREAD

**Issue by the-vampiire** [chingu-x/chingu-connect#31]

**Comment by Bigghead** [comment]
user   : returns single user
- returns an instance of the User model
- it has all fields that the mock user has
- returned User id === mock user id

users : returns all users
- returns an array
- all elements in array are of the User model instances
- returned users' ids === mock users' ids


created : returns user's created connections
- called with `owner` instance
- returns an array
- returns length of 1 ( only mocking 1 connection )
- array elements are of the Connection model
- element's id ==== mock connection id

joined : returns user's joined connections
- called with `partner` instance
- returns an array
- returns length of 1 ( only mocking 1 connection )
- array elements are of the Connection model
- element's id ==== mock connection id
